version: '3',
services:
  proxy:
    image: coutinhojhon/jenkins
    container_name: vector
    build:
      context: .
    ports:
      - "80:8080"
    networks:
      - webservereth
networks:
  webservereth:
    driver: bridge
